theme: jekyll-theme-minimal
title: Hongye Guo
description: [
    "Post Doc. at Tsinghua University."
    "Beijing, China."
    "email: hyguo@mail.tsinghua.edu.cn"
    "google scholar: https://scholar.google.com/citations?user=Op30vHIAAAAJ&hl=zh-CN"
]
logo: pic.jpg

