theme: jekyll-theme-minimal
title: Hongye Guo
description:
    'Post Doc. at Tsinghua University. \n
    Beijing, China. \n
    hyguo@mail.tsinghua.edu.cn \n
    https://scholar.google.com/citations?user=Op30vHIAAAAJ&hl=zh-CN'
logo: pic.jpg

