theme: jekyll-theme-minimal
title: Hongye Guo
author: Hongye Guo
description: |
    Post Doc. at Tsinghua University.

    Beijing, China.

    hyguo@mail.tsinghua.edu.cn
    
    https://scholar.google.com/citations?user=Op30vHIAAAAJ&hl=zh-CN
logo: pic.jpg

